name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-root
        poetry run pip install coverage pytest-cov
    - name: Run pytest
      run: |
        poetry run pytest --cov=onebot -nauto
        poetry run coverage lcov
    - name: Run black
      run: |
        poetry run black --check .
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v2.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.python-version }}
        parallel: true
        path-to-lcov: coverage.lcov
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
